# File: kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: #-> the manifest that we want to customise
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml

patchesStrategicMerge:
  - insecure-patch.yaml
  