apiVersion: v1
kind: Pod
metadata:
  name: app3
  labels:
    app: app3
spec:
  containers:
    - name: hello-kubernetes
      image: paulbouwer/hello-kubernetes:1.10
      env:
        - name: MESSAGE
          value: "Hello from app3."
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080