apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
    - name: hello-kubernetes
      image: paulbouwer/hello-kubernetes:1.10
      env:
        - name: MESSAGE
          value: "Hello from app1."
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 