apiVersion: v1
kind: Pod
metadata:
  name: app3
  labels:
    app: app3
spec:
  containers:
  - image: nginx:latest
    name: app3
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: app3-volume
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  volumes:
  - name: app3-volume
    hostPath:
      path: /vagrant/volumes/app3/
      type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: app3
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30002
  type: NodePort