apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:                
    app: website         
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort