Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine312"

  # Define the master node
  config.vm.define "abdel-ouS" do |master|
    master.vm.hostname = "abdel-ouS"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1028"
      vb.cpus = 1
      vb.name = 'abdel-ouS'
    end
    master.vm.provision "shell", path: "k3s-master.sh"
    master.vm.synced_folder ".", "/vagrant"
  end

end