Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine312"

  # Define the master node
  config.vm.define "k3s-master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = 'abdel-ouS'
    end
    master.vm.provision "shell", path: "k3s-master.sh"
    master.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "k3s-worker1" do |worker1|
    worker1.vm.hostname = "k3s-worker1"
    worker1.vm.network "private_network", ip: "192.168.56.11"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = 'abdel-ouSW'
    end
    worker1.vm.synced_folder ".", "/vagrant"
    worker1.vm.provision "shell", path: "k3s-worker.sh", args: ["192.168.56.10"]
  end 
end