Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine312"
  config.vm.box_version = "4.3.12"

  # Define the master node
  config.vm.define "abdel-ouS" do |master|
    master.vm.hostname = "abdel-ouS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = 'abdel-ouS'
    end
    master.vm.provision "shell", path: "./scripts/k3s-master.sh"
    master.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "abdel-ouSW" do |worker1|
    worker1.vm.hostname = "abdel-ouSW"
    worker1.vm.network "private_network", ip: "192.168.56.111"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = 'abdel-ouSW'
    end
    worker1.vm.synced_folder ".", "/vagrant"
    worker1.vm.provision "shell", path: "./scripts/k3s-worker.sh", args: ["192.168.56.110"]
  end 
end