apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  override.rb: |
    external_url "http://localhost:8080"
  create-admin-user.sh: |
    #!/bin/bash
    gitlab-rails runner "
    user = User.find_or_initialize_by(email: 'eloualy2021@gmail.com')
    user.name = 'Administrator'
    user.username = 'abdel-ou'
    user.password = 'Facebook2000@'
    user.password_confirmation = 'Facebook2000'
    user.admin = true
    user.save!
    puts 'Admin user created successfully' if user.persisted?
    "
---
apiVersion: v1
kind: Pod
metadata:
  name: gitlab-pod
  namespace: gitlab
  labels:
    app: gitlab
spec:
  initContainers:
    - name: create-admin-user
      image: gitlab/gitlab-ce:latest
      command: ["/bin/bash", "/scripts/create-admin-user.sh"]
      volumeMounts:
        - name: gitlab-scripts
          mountPath: /scripts
  containers:
    - name: gitlab-container
      image: gitlab/gitlab-ce:latest
      ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
      volumeMounts:
        - name: gitlab-config-volume
          mountPath: /etc/gitlab/conf.d/override.rb
          subPath: override.rb
  volumes:
    - name: gitlab-config-volume
      configMap:
        name: gitlab-config
    - name: gitlab-scripts
      configMap:
        name: gitlab-config
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: LoadBalancer
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 22