apiVersion: v1
kind: Pod
metadata:
  name: gitlab-pod
  labels:
    app: gitlab
spec:
  containers:
    - name: gitlab-container
      image: gitlab/gitlab-ce:latest
      ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: LoadBalancer
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 8080       # External port for HTTP
      targetPort: 80   # Internal port for HTTP
    - name: https
      protocol: TCP
      port: 8443       # External port for HTTPS
      targetPort: 443  # Internal port for HTTPS
    - name: ssh
      protocol: TCP
      port: 2222       # External port for SSH
      targetPort: 22   # Internal port for SSH