apiVersion: v1
kind: Pod
metadata:
  name: gitlab-pod
  labels:
    app: gitlab
spec:
  containers:
    - name: gitlab-container
      image: gitlab/gitlab-ce:latest
      ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: LoadBalancer
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 22